### ISSUE TITLE
fm代码是否有错误？

### ISSUE THREAD

**Issue by mladl** [Hourout/CTR-keras#1]
FM代码22行 
b = K.dot(x, K.pow(self.kernel, 2))；
从论文公式看不应该是 b = K.dot(K.pow(x, 2), K.pow(self.kernel, 2))吗

**Comment by naihaishy** [comment]
应该是b = K.dot(K.pow(x, 2), K.pow(self.kernel, 2))

**Comment by Hourout** [comment]
thank you @BanmaBanma @naihaishy
